<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="hostgator.TestMadeToFail" duration-ms="32235" started-at="2019-10-29T14:20:19 CDT" finished-at="2019-10-29T14:20:51 CDT">
    <groups>
      <group name="SmokeTest">
        <method signature="TestMadeToFail.TestMadeToFail()[pri:0, instance:hostgator.TestMadeToFail@62379589]" name="TestMadeToFail" class="hostgator.TestMadeToFail"/>
      </group> <!-- SmokeTest -->
      <group name="SignupRegression">
        <method signature="TestMadeToFail.TestMadeToFail()[pri:0, instance:hostgator.TestMadeToFail@62379589]" name="TestMadeToFail" class="hostgator.TestMadeToFail"/>
      </group> <!-- SignupRegression -->
    </groups>
    <test name="Command line test" duration-ms="32235" started-at="2019-10-29T14:20:19 CDT" finished-at="2019-10-29T14:20:51 CDT">
      <class name="hostgator.TestMadeToFail">
        <test-method status="PASS" signature="initialize()[pri:0, instance:hostgator.TestMadeToFail@62379589]" name="initialize" is-config="true" duration-ms="26917" started-at="2019-10-29T14:20:19 CDT" finished-at="2019-10-29T14:20:46 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="TestMadeToFail()[pri:0, instance:hostgator.TestMadeToFail@62379589]" name="TestMadeToFail" duration-ms="5165" started-at="2019-10-29T14:20:46 CDT" finished-at="2019-10-29T14:20:51 CDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[TestMadeToFail did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: TestMadeToFail did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at hostgator.TestMadeToFail.TestMadeToFail(TestMadeToFail.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestMadeToFail -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:hostgator.TestMadeToFail@62379589]" name="teardown" is-config="true" duration-ms="131" started-at="2019-10-29T14:20:51 CDT" finished-at="2019-10-29T14:20:51 CDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- hostgator.TestMadeToFail -->
    </test> <!-- Command line test -->
  </suite> <!-- hostgator.TestMadeToFail -->
</testng-results>
